server:
  port: 8080

spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:reserva-db
    username: sa
    password:
    driverClassName: org.h2.Driver